---
# ansible-playbook build-server.yaml --ask-pass
- hosts: web
  tasks:
    - name: Install prerequisites (ติดตั้งโปรแกรมเบื้องต้น)
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
          ]
        update_cache: yes

    - name: Install additional package (ติดตั้งโปรแกรมเพิ่มเติม)
      apt:
        name: ["zip", "unzip"]

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install Docker
      apt: name=docker-ce

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
